dist: trusty
sudo: false
language: cpp python
before_install:
  - pip install -U pytest
install:
script:
  - CXX="g++-4.8" CC="gcc-4.8" LDFLAGS="-lrt -Wl,--no-as-needed" MAKEOPTS="-l 1.5" ./build.sh
  - travis_wait 60 make check
  - cat test-suite.log
after_failure:
  - echo "Sad memking"
  - find . -name config.log -exec cat {} ";"
  - find . -name test-suite.log -exec cat {} ";"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libnuma-dev
    - numactl
notifications:
  email:
    recipients:
      - krzysztof.kulakowski@intel.com
      - lukasz.anaczkowski@intel.com
    on_success: [change]
    on_failure: [always]
